### ISSUE TITLE
Page scroll is borked on Android devices

### ISSUE THREAD

**Issue by jimmynguyc** [rubyconfmy/rubyconfmy.github.io#1]
It's stuck on the top of the page. Works fine on iOS.

**Comment by lex111** [comment]
@jimmynguyc assign to me please, I'll try fix.

**Comment by jimmynguyc** [comment]
Thanks @lex111 .. I've added you as collaborator. Feel free to make create PR for this :)

**Comment by lex111** [comment]
@jimmynguyc accepted the invitation, now try to assign.

**Comment by lex111** [comment]
Created PR #2.
